### ISSUE TITLE
Calling script cpane often fails with system perl

### ISSUE THREAD

**Issue by andk** [oklas/cpanexec#1]
OKLAS/App-cpanexec-0.03.tar.gz pass to fail ratio is very low. My first glance into the test script reveals:

https://metacpan.org/source/OKLAS/App-cpanexec-0.03/t/01_execute.t#L15

    system "$cwd/script/cpane", @args;

This will try to run the script with system perl, not the one you are trying to test. I'd suggest to change that to

    system $^X, "$cwd/script/cpane", @args;

I have not tried whether this is enough, but it's a good first step towards more success.

**Comment by oklas** [comment]
Thank you! Good suggestion! Happy new year!
