### ISSUE TITLE
Missing requirements?

### ISSUE THREAD

**Issue by eserte** [oklas/cpanexec#2]
On some of my smoker systems the test suite fails:
```
#   Failed test 'folder "./local" is required'
#   at t/01_execute.t line 34.

#   Failed test 'script or command is required'
#   at t/01_execute.t line 34.

#   Failed test 'env is configured to load libraries'
#   at t/01_execute.t line 34.

#   Failed test 'env is configured to execute binary'
#   at t/01_execute.t line 34.
# Looks like you failed 4 tests of 4.
t/01_execute.t .. 
Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/4 subtests 
```
It seems that in these cases prerequisites are missing, at least `local::lib`.

**Comment by eserte** [comment]
0.04 and 0.05 are affected.

**Comment by eserte** [comment]
Hmmm. I don't see any real diffs:
https://metacpan.org/diff/file?target=OKLAS/App-cpanexec-0.06/&source=OKLAS%2FApp-cpanexec-0.05

**Comment by eserte** [comment]
Hmmm, still no "local::lib" in the requirements...

**Comment by oklas** [comment]
Thank you! Shade is caught! Happy new year!
